version: '3.8'
services:
  redis_local:
    image: redis:6.2-alpine
    container_name: redis_local
    #    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass root
#    volumes:
#      - cache_redis_local:/data
#    networks:
#      - redis_local
#
#volumes:
#  cache_redis_local:
#    driver: local
#
#networks:
#  redis_local: