version: '3.8'

services:
  mongodb1:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27018:27017"
#    volumes:
#      - mongodb_realworld:/data/db
#
#volumes:
#  mongodb_realworld:
