version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=es_local
      - node.name=es_lcl-1
      - discovery.type=single-node
      - xpack.security.enabled=false